"""Patch md_to_ieee_tex.py: replace the PREAMBLE variable with a pure-ASCII version."""
src = open("md_to_ieee_tex.py", encoding="utf-8").read()

old_marker_start = "PREAMBLE = r\"\"\""
old_marker_end   = "\"\"\"\n\nPOSTAMBLE"

# Find and replace the preamble block
start = src.index(old_marker_start)
end   = src.index(old_marker_end) + len(old_marker_end)

new_preamble = r'''PREAMBLE = r"""% ==============================================================
%  UPI Fraud Shield ML -- IEEE Transactions Manuscript
%  Auto-generated by md_to_ieee_tex.py (do not edit directly)
% ==============================================================
\documentclass[journal,10pt,twocolumn]{IEEEtran}

% -- Packages --------------------------------------------------
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}          % professional table rules
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{cite}
\usepackage{url}
\usepackage{textcomp}
\usepackage{microtype}
\usepackage{balance}
\usepackage{upgreek}

% Rupee symbol (ASCII-safe definition)
\newcommand{\rupee}{\text{\textsf{Rs.}}}

% -- Hyperref colours ------------------------------------------
\hypersetup{
  colorlinks = true,
  linkcolor  = blue,
  citecolor  = blue,
  urlcolor   = blue
}

% --------------------------------------------------------------
\begin{document}
"""

POSTAMBLE'''

patched = src[:start] + new_preamble + src[end:]
open("md_to_ieee_tex.py", "w", encoding="utf-8").write(patched)
print("Patched preamble OK")
